In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [3]:
def printme(nama):  #PARAMETER #nama holds value yansen/ nama saya adalah...
   "This prints nama string into this function"
   print(nama)

In [4]:
printme("yansen") #ARGUMEN

yansen


In [5]:
printme("nama saya adalah...")

nama saya adalah...


In [18]:
def printme(nama,alamat):  #PARAMETER #nama holds value yansen/ nama saya adalah...
   "This prints nama string into this function"
   print(nama)
    print(alamat)

IndentationError: unexpected indent (<ipython-input-18-8fc4d656bc0c>, line 4)

In [19]:
printme("yansen", "Bekasi")

TypeError: printme() takes 1 positional argument but 2 were given

In [28]:
def printme(nama = "yansen", alamat = "Bekasi"):  
   "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

IndentationError: unexpected indent (<ipython-input-28-b125fdb9c8d8>, line 3)

In [29]:
printme()

TypeError: printme() missing 1 required positional argument: 'nama'

In [30]:
def printinfo( arg1, *vartuple ):
   "This prints a variable passed arguments"
   print("Output is: ")
   print(arg1)
   for var in vartuple:
      print(var)
   return;

Output is: 
10
Output is: 
70
60
50


In [31]:
printinfo( 30 )

Output is: 
30


In [32]:
printinfo( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 )

Output is: 
1
2
3
4
5
6
7
8
9
10


In [33]:
sum = lambda arg1, arg2: arg1 + arg2;

In [34]:
sum(10,20)

30

In [36]:
print("Value of total : ", sum( 20, 20 ))

Value of total :  40


In [44]:
def sum( arg1, arg2 ):
    total = arg1 + arg2
    total1 = total + 50
    return total1

In [45]:
sum( 10, 20 )

80

In [61]:
kucing = 20

def jumlahHewan():
    kelinci = 40
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [59]:
jumlahHewan()

60

In [62]:
tambahHewan()

40

In [63]:
import sys

In [64]:
sys.path

['C:\\Users\\ASUS',
 'C:\\Users\\ASUS\\anaconda3\\python37.zip',
 'C:\\Users\\ASUS\\anaconda3\\DLLs',
 'C:\\Users\\ASUS\\anaconda3\\lib',
 'C:\\Users\\ASUS\\anaconda3',
 '',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ASUS\\.ipython']

In [66]:
sys.path.append(r'/Users/ASUS/Desktop/H8package/')

In [67]:
sys.path

['C:\\Users\\ASUS',
 'C:\\Users\\ASUS\\anaconda3\\python37.zip',
 'C:\\Users\\ASUS\\anaconda3\\DLLs',
 'C:\\Users\\ASUS\\anaconda3\\lib',
 'C:\\Users\\ASUS\\anaconda3',
 '',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ASUS\\.ipython',
 '/Users/ASUS/Desktop/H8package/']

In [70]:
import mod

In [71]:
mod.s

'Hacktiv8 Inalum for Data Science'

In [72]:
mod.a

[100, 200, 300]

In [76]:
mod.foo("yansen")

yansen


In [74]:
from mod import s, foo

In [75]:
s

'Hacktiv8 Inalum for Data Science'

In [77]:
foo("yansen")

yansen


In [78]:
from mod import *

In [79]:
s

'Hacktiv8 Inalum for Data Science'

In [80]:
from mod import s as string

In [81]:
string

'Hacktiv8 Inalum for Data Science'

In [82]:
import mod as my_module

In [83]:
my_module.a

[100, 200, 300]

In [84]:
my_module.s

'Hacktiv8 Inalum for Data Science'

In [85]:
import numpy as np

In [86]:
import H8package.mod

H8package.mod.s

ModuleNotFoundError: No module named 'H8package'

In [87]:
from H8package.mod import s

ModuleNotFoundError: No module named 'H8package'

In [89]:
s

'Hacktiv8 Inalum for Data Science'

In [90]:
sys.path.append(r'/Users/ASUS/Desktop/')

In [91]:
import H8package.mod

H8package.mod.s

'Hacktiv8 Inalum for Data Science'

In [92]:
from H8package.mod import s

In [93]:
s

'Hacktiv8 Inalum for Data Science'

In [94]:
!pip --version

pip 20.0.2 from C:\Users\ASUS\anaconda3\lib\site-packages\pip (python 3.7)



In [95]:
!pip install requests

In [96]:
import requests

In [97]:
import numpy as np

Creating Array

In [98]:
a = np.array([1, 2, 3])

In [99]:
a

array([1, 2, 3])

In [100]:
b = [1, 2, 3]

In [101]:
b

[1, 2, 3]

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
c = np.zeros(5)

In [104]:
print(c)

[0. 0. 0. 0. 0.]


In [105]:
d = np.ones(5)

In [107]:
print(d)

[1. 1. 1. 1. 1.]


In [109]:
np.arange(4)

array([0, 1, 2, 3])

In [110]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(0, 20, 2) # Start, Stop, Step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [113]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
print(arr)

[1 2 3 4 5 6 7 8]


In [116]:
np.append(arr, [1,2]) # Add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [118]:
np.delete(arr, 1)  # delete

array([1, 3, 4, 5, 6, 7, 8])

In [120]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [121]:
print(arr)

[2 1 5 3 7 4 6 8]


In [123]:
np.sort(arr)  # sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

Shape and Size

In [141]:
array_example = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [142]:
print(array_example)

[[0 1 2 3]
 [4 5 6 7]]


In [143]:
array_example.ndim

2

In [144]:
array_example.size

8

In [145]:
array_example.shape

(2, 4)

## Reshape

In [146]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [147]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [151]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

### Convert 1D to 2D

In [152]:
a

array([0, 1, 2, 3, 4, 5])

In [153]:
a.shape

(6,)

In [155]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [156]:
row_vector = a[np.newaxis]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [158]:
col_vector = a[:, np.newaxis] ## np.newaxis di kiri untuk nambah konten dikiri, dan lakukan sebaliknya jika mau tambah di kanan
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [159]:
print(a.shape)

(6,)


In [160]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [161]:
e = np.expand_dims(a, axis=1)
print(e)
print(e.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


### Indexing and Slicing

In [162]:
data = np.array([1,2,3])

In [163]:
data[0]

1

In [164]:
data[1]

2

In [165]:
data[0:2]

array([1, 2])

In [166]:
data[1:]

array([2, 3])

In [167]:
data[-2]

2

In [168]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [179]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [172]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [173]:
a[a<=8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [176]:
lebih_lima = (a >= 5)

print(a[lebih_lima)

[ 5  6  7  8  9 10 11 12]


In [178]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## create array from existing data

In [180]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
arr1 = arr[3:9]

In [182]:
print(arr1)

[4 5 6 7 8 9]


In [184]:
a_1 = np.array([[1, 1],
                [2, 2]])

print(a_1)

[[1 1]
 [2 2]]


In [186]:
a_2 = np.array([[3, 3],
                [4, 4]])

print(a_2)

[[3 3]
 [4 4]]


In [187]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [188]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [189]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [191]:
np.hsplit(arr,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [192]:
## View dan Copy

In [193]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [194]:
b = a.view()

In [195]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [196]:
c = a.copy()

In [197]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [198]:
### basic array operation

In [199]:
a_1

array([[1, 1],
       [2, 2]])

In [200]:
a_2

array([[3, 3],
       [4, 4]])

In [201]:
a_2 - a_1

array([[2, 2],
       [2, 2]])

In [202]:
a_2 + a_1

array([[4, 4],
       [6, 6]])

In [203]:
a_2 * a_1

array([[3, 3],
       [8, 8]])

In [204]:
a_2 / a_1

array([[3., 3.],
       [2., 2.]])

In [205]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [206]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [207]:
arr.sum()

55

In [208]:
a_1

array([[1, 1],
       [2, 2]])

In [209]:
a_1.sum()

6

In [210]:
a_1.sum(axis=0)

array([3, 3])

In [211]:
a_1.sum(axis=1)

array([2, 4])

In [213]:
print(a_1)

[[1 1]
 [2 2]]


In [214]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [215]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [216]:
a.sum()

78

In [217]:
a.min()

1

In [218]:
a.max()

12

In [219]:
a.min(axis=0)

array([1, 2, 3, 4])

In [220]:
a.min(axis=1)

array([1, 5, 9])

In [221]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [222]:
a.max(axis=1)

array([ 4,  8, 12])

In [223]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [224]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [225]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [226]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [227]:
np.random.random((3,2))

array([[0.27793341, 0.71675159],
       [0.32512882, 0.56113123],
       [0.12737205, 0.25632345]])

In [228]:
## matric aritmetic

In [229]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [230]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [231]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [232]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [233]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [234]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [235]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [236]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [237]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [238]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [239]:
data[0,1]

2

In [240]:
data[1,1]

4

In [244]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [245]:
data[0:2,0]

array([1, 3])

In [246]:
### matrix agregetion

In [247]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [248]:
data.min()

1

In [249]:
data.max()

6

In [250]:
data.sum()

21

In [251]:
data.max(axis=1)

array([2, 4, 6])

In [252]:
data.max(axis=0)

array([5, 6])

In [253]:
## transposing and reshaping

In [254]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [255]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [256]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [257]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [258]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [262]:
arr = np.arange(6).reshape((2, 3))

In [260]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [263]:
## ND array

In [264]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])


In [265]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [266]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [267]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [269]:
np.random.random((4,3,2))

array([[[0.05964454, 0.52924093],
        [0.43141975, 0.50140349],
        [0.12302082, 0.02078016]],

       [[0.8980413 , 0.01949385],
        [0.6290114 , 0.85280067],
        [0.60450611, 0.01849106]],

       [[0.73225538, 0.14538023],
        [0.78676682, 0.76774015],
        [0.13644472, 0.26133097]],

       [[0.34996611, 0.00752042],
        [0.82978276, 0.98408882],
        [0.1829917 , 0.12394285]]])

In [270]:
## flatten

In [271]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [272]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [286]:
a = np.random.rand(5, 1)

In [287]:
print(a)

[[0.88864465]
 [0.96577365]
 [0.59759692]
 [0.81332354]
 [0.85512458]]


In [288]:
a.shape # rank 1 array

(5, 1)

In [289]:
a.T

array([[0.88864465, 0.96577365, 0.59759692, 0.81332354, 0.85512458]])

In [290]:
np.dot(a, a.T)

array([[0.78968932, 0.85822958, 0.5310513 , 0.72275561, 0.75990189],
       [0.85822958, 0.93271873, 0.57714335, 0.78548644, 0.82585679],
       [0.5310513 , 0.57714335, 0.35712208, 0.48603964, 0.51101982],
       [0.72275561, 0.78548644, 0.48603964, 0.66149517, 0.69549295],
       [0.75990189, 0.82585679, 0.51101982, 0.69549295, 0.73123805]])

In [291]:
a = np.random.rand(1, 5)

In [292]:
a.shape

(1, 5)

In [293]:
a

array([[0.37011326, 0.95159875, 0.80932118, 0.93956149, 0.8822061 ]])

In [294]:
ndarr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

In [295]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
ndarr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])